### ISSUE TITLE
Heartbeat stops when app pool hosted endpoint recycles (Monitored from ServicePulse)

### ISSUE THREAD

**Issue by JoeShook** [Particular/ServiceControl.Plugin.Nsb5.Heartbeat#7]
Specific endpoint is a Sendonly endpoint.
First noticed this in a high load environment.  When the w3wp.exe was recycled the heartbeat would fail from then on.

Tried this locally in development.  Killing the process and restarting it with a web request results in losing the heartbeat also.  If I recompile with changing the code first ensures the heartbeat returns.  Seems there is some kind of hashing algorithm that gets out of sync.

**Comment by dannycohen** [comment]
See http://docs.particular.net/servicepulse/troubleshooting#asp-net-applications-heartbeat-failure

**Comment by JoeShook** [comment]
From the docs referenced;

The issue is due to the way IIS handles application pools. By default after
a certain period of inactivity the application pools is stopped, or, under
certain configurable conditions, the application pool is recycled. In both
cases the ServicePulse heartbeat is not sent anymore until a new web
request comes in waking up the web application.

In my case I am sending new web requests to start the app pool, but from
that point forward the heartbeat no longer exists.  Also note, I am using
the RabbitMQ transport.

**Comment by danielmarbach** [comment]
I just verified that behavior but it is not an issue of the heartbeat plugins. It is related to how IIS needs to be configured. The problem is the following. Although you have the ApplicationPool configured to be always running that doesn’t mean the page gets properly preloaded to start the bus instance and the associated plugins. You can verify it by

1. Recycling the Application Pool
1. Switch to Service Pulse, wait for the heartbeat interval to run up
1. See how the endpoint turns red
1. Go to the website and refresh the page
1. Switch to ServicePulse and see how the endpoint is green again

In order to fix that you need to do the following in addition to having the ApplicationPool as always on:

1. Enabled Preload for the site itself (right click on the site then Manage Site then Advanced Settings in the General settings, Enable Preload true)
1. Install the Application Initialization Module as described here http://www.iis.net/learn/get-started/whats-new-in-iis-8/iis-80-application-initialization
1. Add the following to your web.config under the <system.webServer> node

```
<applicationInitialization doAppInitAfterRestart="true" > 
<add initializationPage="/" />
</applicationInitialization>
```

Finally, Redeploy

This should resolve your issue.

This only works with IIS 7.5 and higher
